### ISSUE TITLE
Please add a license

### ISSUE THREAD

**Issue by karan** [pwnall/seven#104]
Without a license, this project isn't open source and no one can use the code.

Please use something like http://choosealicense.com/ to decide what license to use. I recommend MIT or GPL.

**Comment by pwnall** [comment]
@karan Thanks for the heads up!

MIT license added in 533128847f61f9a9e397f2bb0224bb380ca5be0e

For anyone reading, assigning the copyright to MIT has nothing to do with the license name. The Institute paid (and is still paying) for a good amount of the work done in this repository.
