### ISSUE TITLE
Reversed pull/release buttons on team partitions

### ISSUE THREAD

**Issue by spark008** [pwnall/seven#110]
I think the `TeamPartitionsController#unlock` action should actually set the `editable` attribute to `false`, not `true`. Or maybe I'm misunderstanding what the `editable` attribute means. In any case, when you click the 'unlock' link, the view doesn't change to show the 'lock' link.

**Comment by pwnall** [comment]
Fixed in b8fd866ed4afd467dfb45f1e79bb400c56682383
