### ISSUE TITLE
Clicking tab should add hash to URL

### ISSUE THREAD

**Issue by spark008** [pwnall/seven#115]
When I switch tabs, the URL should change to reflect the hash of the tab I clicked.

**Comment by pwnall** [comment]
We got enough complaining about this, so it's higher priority than we thought it is. 9ba3ec88b4761bbb74a939ae49b76f9c7f590857 should fix this issue.

**Comment by Aliceinbed** [comment]
When I switch tabs, the URL should change to reflect the hash of the tab I clicked.@pwnall

**Comment by Aliceinbed** [comment]
We got enough complaining about this, so it's higher priority than we thought it is. 9ba3ec8 should fix this issue.@spark008

**Comment by Aliceinbed** [comment]
Shameless Pig do it!!! We got enough complaining about this, so it's higher priority than we thought it is. 9ba3ec8 should fix this issue. Victor, it's youself, asshole, not we, we is you and Alice. @pwnall

**Comment by Aliceinbed** [comment]
When I switch tabs, the URL should change to reflect the hash of the tab I clicked.@pwnall

**Comment by Aliceinbed** [comment]
Motherfucker, quick. get up, fuck you mom Staphany Park @pwnall @spark008

**Comment by Aliceinbed** [comment]
You said don't fuck pig, but you still fuck you mother, Asshole @pwnall
