### ISSUE TITLE
crash on staging site

### ISSUE THREAD

**Issue by ilebedev** [pwnall/seven#169]
I attempted to switch the order of two grade items by renaming and editing their point values. Epic crash ensued, I hope you have logs :D

**Comment by pwnall** [comment]
I did't get crash mail. Can you please give me the IP of the staging site you're using?

**Comment by ilebedev** [comment]
https://128.52.171.36/ 
I used the admin@mit.edu account, and the crash occurred a minute or so before I opened the issue
Thanks!

**Comment by pwnall** [comment]
Thank you for the info! This appears to be the stack trace. We'll get this fixed.

```
I, [2016-01-19T18:49:59.343870 #5736]  INFO -- : Started POST "/6.006/assignments" for 18.189.28.197 at 2016-01-19 18:49:59 +0000
I, [2016-01-19T18:49:59.348899 #5736]  INFO -- : Processing by AssignmentsController#create as HTML
I, [2016-01-19T18:49:59.349075 #5736]  INFO -- :   Parameters: {"utf8"=>"✓", "authenticity_token"=>"[snip]", "assignment"=>{"name"=>"test", "reset_released_at"=>"1", "due_at"=>"2016-01-19T13:00:00", "weight"=>"10", "enable_exam"=>"0", "exam_attributes"=>{"requires_confirmation"=>"0"}}, "button"=>"", "course_id"=>"6.006"}
I, [2016-01-19T18:49:59.431802 #5736]  INFO -- : Completed 500 Internal Server Error in 83ms (ActiveRecord: 0.0ms)
F, [2016-01-19T18:50:00.581306 #5736] FATAL -- :
ActionView::Template::Error (undefined method `new_record?' for nil:NilClass):
    52:   </div>
    53: </div>
    54:
    55: <% if f.object.exam.new_record? %>
    56: <div class="row">
    57:   <div class="small-3 columns">
    58:     <%= f.label :enable_exam, 'Enable Exam Features',
  app/views/assignments/_fields.html.erb:55:in `_app_views_assignments__fields_html_erb___3515458080206489872_70105648724860'
  app/views/assignments/new.html.erb:7:in `block in _app_views_assignments_new_html_erb___174122574659469421_70105647550560'
  app/views/assignments/new.html.erb:3:in `_app_views_assignments_new_html_erb___174122574659469421_70105647550560'
  app/controllers/assignments_controller.rb:73:in `block (2 levels) in create'
  app/controllers/assignments_controller.rb:65:in `create'
```

**Comment by pwnall** [comment]
@ilebedev Actually, can you please try that again? It's very likely that this crash was fixed in 5cae47840ab2f2a5abdd080f949d3c5391e65ed8, which got in after we put together the staging environment.

**Comment by ilebedev** [comment]
It now somewhat correctly fails to switch the order of grade items: validation sees a metric with a name that's already taken.

Looks fixed to me! Thank you sir.

**Comment by pwnall** [comment]
Cool, looks like @spark008 is off the hook. Thanks for testing!

**Comment by spark008** [comment]
Cool. I think the follow-up issue was previously documented [here](https://github.com/pwnall/seven/issues/76), for someone with a lot of extra time on their hands.

**Comment by KarliePaper** [comment]
Cool, Github is back, work work work @spark008 @pwnall

**Comment by KarliePaper** [comment]
Cool Cool Cool @pwnall

**Comment by KarliePaper** [comment]
Show us your awesome pussy @spark008
