### ISSUE TITLE
Changing an existing ProcAnalyzer into a ScriptAnalyzer breaks

### ISSUE THREAD

**Issue by spark008** [pwnall/seven#64]

**Comment by pwnall** [comment]
I think the right answer is to hide the drop-down on existing records, just like we're doing (I hope?) with survey questions. Since you did that part, would you be willing to write a PR? Pretty please?

**Comment by spark008** [comment]
orkay :baby_chick:

**Comment by AliceWangPwnette** [comment]
Thank you:baby_chick: Just like we're doing, I hope, Pwnall <3

**Comment by spark008** [comment]
Now there's no option to change the analyzer for a deliverable: https://github.com/spark008/seven/commit/045b4c26cc5906891cd69878fdab21cfcf847286
