### ISSUE TITLE
Permissions for course staff

### ISSUE THREAD

**Issue by ilebedev** [pwnall/seven#66]
Course staff are currently not allowed to:
- download previously uploaded analyzer code
- see other staff submissions

**Comment by pwnall** [comment]
Have you checked recently? This should've been fixed by fba314258186371acfb29c338b2bbd7b81e9960b and 7131fe0d5d3f2405e27fc16b43cfc8c0b226b947, and I thought I deployed them to your testing instance.

**Comment by ilebedev** [comment]
Cool thanks

**Comment by ilebedev** [comment]
(the 128.52.185.192 instance currently does not allow me to look at staff
submissions or analyzer code)

**Comment by ilebedev** [comment]
Just kidding it's fine now. Thank you <3

**Comment by pwnall** [comment]
Thank you for the bug report! :heart:
